### ISSUE TITLE
[docs] incosistency `expected_ip_cidr` vs `expected_cidr_range` 

### ISSUE THREAD

**Issue by smrqdt** [vatesfr/terraform-provider-xenorchestra#320]
There seems to be an inconsistency in the registry docs with the new network parameter that replaces `wait_for_ip`.

In the [registry documentation](https://registry.terraform.io/providers/vatesfr/xenorchestra/latest/docs/resources/vm#expected_ip_cidr) the argument is called `expected_ip_cidr` while in the [release notes](https://github.com/vatesfr/terraform-provider-xenorchestra/releases/tag/v0.29.0) it’s `expected_cidr_range`. 

The string `expected_ip_cidr` [does not appear anywhere in the repository](https://github.com/search?q=repo%3Avatesfr%2Fterraform-provider-xenorchestra+expected_cidr_range&type=code) except the commit message, so I guess it’s wrong but somehow made its way into the terraform registry.

**Comment by ddelnano** [comment]
Hi @smrqdt, thanks for spotting this. The release notes are incorrect and I've updated them. The documentation is auto generated from the terraform code so the docs are correct.

The link you provided for searching for `expected_ip_cidr` doesn't seem to identify [this](https://github.com/vatesfr/terraform-provider-xenorchestra/blob/3fab225b26e0d9b2f293a2f952a4a138ebd56ace/xoa/resource_xenorchestra_vm.go#L354).
